#!/bin/sh

#eval "$(direnv hook zsh)"
# PATH=/Users/lehoff/.nix-profile/bin:/nix/var/nix/profiles/default/bin:$PATH
# eval "$(fasd --init auto)"

function rebuild_nix {
  darwin-rebuild build --flake ./\#$1
  darwin-rebuild switch --flake ./\#$1
}
